---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels: 
        app: node
    spec:
      containers:
        - image: gcr.io/kodekloud/centos-ssh-enabled:node
          name: node-app-cont
          ports:
            - containerPort: 8080
              name: node-app
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30012

