apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: devops
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.28
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 2
     maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
 name: httpd-service
 namesapce: devops
spec:
  type: NodePort
  selector:
   app: httpd
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30008

