apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-namespace-devops
  labels:
    name: tomcat-namespace-devops-ns
---
apiVersion: v1
kind: Deployment
metadata:
  name: tomcat-deployment-devops
  namespace: tomcat-namespace-devops
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
        containers:
         - name: tomcat-container-devops
           image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
           port: 8080
---                                                                                                           
apiVersion: v1                                                                                     
kind: Service                                                                                             
metadata:                                                                                                
  name: tomcat-service-devops                                                                                namespace: tomcat-namespace-devops 
spec:                                                                                                    
   type: NodePort                                                                                         
   selector:                                                                                               
     app: tomcat                                                                          
   ports:                                                                                                  
     - port: 8080                                                                                         
       targetPort: 8080                                                                                
       nodePort: 32227
