---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx  
    spec:
        containers:
         - name: nginx-container
           image: nginx:latest
---                                                                                                           
apiVersion: v1                                                                                     
kind: Service                                                                                             
metadata:                                                                                                
  name: nginx-service                                                                                      
spec:                                                                                                    
   type: NodePort                                                                                         
   selector:                                                                                               
     app: nginx                                                                                        
   ports:                                                                                                  
     - port: 8098                                                                                         
       targetPort: 8098                                                                                   
       nodePort: 30011
