apiVersion: v1
kind: Pod
metadata: 
    - name: volume-share-devops
spec:
    containers:
    - name: volume-container-devops-1
      image: centos:latest
      command:["sleep","10000"]
      volumeMounts:
        - mountPath: "/tmp/official"
          name: volume-share
    - name: volume-container-devops-2
      image: centos:latest
      command:["sleep","10000"]
      volumeMounts:
        - mountPath: "/tmp/games"
          name: volume-share
    volumes:
    - name: volume-share
      emptyDir: {}
