apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
  containers:
    - name: volume-container-datacenter-1
      image: centos:latest
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/official
    - name: volume-container-datacenter-2
      image: centos:latest
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/demo


run command under any container
kubectl exec -it <pod_name> -c <container_name> — /bin/bash
